### PR TITLE
Correlation matrix report (replaces PR #52)

### PR DESCRIPTION
**Pull request by conradoqg**
Hey,

Here is the correlation matrix report (originally from PR #52) merged to the latest commit.

If this is accepted we can close the PR #52.

Best.

### CODE REVIEW

**Comment by conradoqg** [comment]
Hey @romainx, I have a new set of improvements to fulfill the issue #35 I'll create a new PR after you merge this one.

Sorry to be giving you a lot of work and thanks for your time. I'm trying to help you guys clean the issue/PR list and at the same time improve my pandas skills.

Best

**Comment by romainx** [comment]
Hello @JosPolfliet @conradoqg,

Do you want me to merge this PR on the master?
I can do it today.

Thanks

**Comment by conradoqg** [comment]
OK. Let's do it!

**Comment by conradoqg** [comment]
I'm disabling by default the check_recoded (the feature responsible for the instability of large datasets), I also updated the documentation about it.

**Comment by romainx** [comment]
Very good job. Nothing to add. I'm glad to see that the new module organization brings more clarity 😉

**Comment by romainx** [comment]
Just a remark sorry I've not seen it before.
Should we generate the correlation matrixes when `check_correlation = False`?
I'm not sure.
It's the case in the current implementation.

**Comment by conradoqg** [comment]
Yes, I think we should. The `check_correlation` is used to check highly correlated features (and reject them) and not to determine if we should display the correlation matrix between variables.

The `check_correlation` does a deeper analysis than the matrix anyway.

Best

**Comment by conradoqg** [comment]
I'm not sure anymore about my previous comment. I'm changing this behavior in a new PR related to the issue #40.

I'll do further analysis on the performance of the correlation calculation.

**Pull request merged**
