### PR TITLE
Detect dtype from pandas df

### PR DESCRIPTION
**Pull request by sbrugman**
Supersedes https://github.com/pandas-profiling/pandas-profiling/pull/680

### CODE REVIEW

**Comment by mohith7548** [comment]
Thanks for accepting the PR. 
This is my first open-source contribution & I feel appreciated.

**Comment by mohith7548** [comment]
Hey @sbrugman, `infer_dtypes` parameter not working after the last two commits you made.
I believe something is breaking in the file `src/pandas_profiling/serialize_report.py` that is changed under commit named `Fix global config`.

Here's the error I encountered after installing latest package(`pip install pandas-profiling==2.10.1`).
```python3
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-08a0c3130916> in <module>
----> 1 df.profile_report(infer_dtypes=False)

c:\users\kune.mohith\appdata\local\continuum\anaconda3\envs\pp\lib\site-packages\pandas_profiling\controller\pandas_decorator.py in profile_report(df, **kwargs)
     15         A ProfileReport of the DataFrame.
     16     """
---> 17     p = ProfileReport(df, **kwargs)
     18     return p
     19 

c:\users\kune.mohith\appdata\local\continuum\anaconda3\envs\pp\lib\site-packages\pandas_profiling\profile_report.py in __init__(self, df, minimal, explorative, sensitive, dark_mode, orange_mode, sample, config_file, lazy, **kwargs)
     78             config.set_arg_group("orange_mode")
     79 
---> 80         config.set_kwargs(kwargs)
     81 
     82         self.df = None

c:\users\kune.mohith\appdata\local\continuum\anaconda3\envs\pp\lib\site-packages\pandas_profiling\config.py in set_kwargs(self, kwargs)
    146         kwargs = self._handle_shorthands(kwargs)
    147 
--> 148         self._set_kwargs(self.config, kwargs)
    149 
    150     def __getitem__(self, item):

c:\users\kune.mohith\appdata\local\continuum\anaconda3\envs\pp\lib\site-packages\pandas_profiling\config.py in _set_kwargs(self, reference, values)
     95                     reference[key].set(value)
     96             else:
---> 97                 raise ValueError(f'Config parameter "{key}" does not exist.')
     98 
     99     _shorthands = {

ValueError: Config parameter "infer_dtypes" does not exist.
```

Kindly revert back the changes of the commit `Fix global config` in file `src/pandas_profiling/serialize_report.py` to make the package working with `infer_dtypes` again.

**Comment by sbrugman** [comment]
@mohith7548 The changes are merged into our develop branch, but not yet released, so the ValueError is correct. To have early access, you can install using `pip install https://github.com/pandas-profiling/pandas-profiling/archive/develop.zip` (stability not guaranteed).

**Comment by mohith7548** [comment]
Thanks for clearing the confusion.

**Pull request merged**
