### PR TITLE
Added response curves to output. Closes #10

### LINKED ISSUE #10: Ploting a response variable on the histograms
Hey,

Great job with pandas-profiling I love it.
I think it would be great to have an extra parameter to specify a response column.
Plotting the average response for every bin of the histograms (for each variables) would allow to see obvious trends/correlations and would be useful for any regression problem (might be more tricky for classification where the response are discrete).
What do you think ?

Thanks!

### PR DESCRIPTION
**Pull request by andyreagan**

### CODE REVIEW

**Comment by andyreagan** [comment]
This adds a response curve output for all variable types when called with the flag `compute_responses=True`.

Here's an example of the response curve that gets included:
screen shot 2017-06-15 at 5 06 54 pm

**Comment by JosPolfliet** [comment]
Nice! Could you maybe add a parameter 'target' with the name of the target column? Right now, it looks like it has to literally be named 'target'.

**Comment by andyreagan** [comment]
Great idea, I had already started this one.

**Comment by andyreagan** [comment]
@JosPolfliet added the target column option with the latest commits.

I also started to add the option for another backend other than Pandas.
If you don't want to keep that stuff, I would understand.

**Comment by dartdog** [comment]
nice!

**Comment by valtheval** [comment]
Hello, this is a nice feature.
Still, I'm faving problem using it. My pandas-profiling package is up to date but I have the following error when I type
`pandas_profiling.ProfileReport(df, compute_response=True)`

> TypeError: _plot_histogram() got an unexpected keyword argument 'compute_response'

Any help would be really appreciated,
Thanks

**Comment by andyreagan** [comment]
@valtheval that's because you're using the master branch. to use this feature, atm, you'll have to check out this branch load from python there.

**Comment by dartdog** [comment]
Would love to see this merged to master!

**Comment by andyreagan** [comment]
Me too!

Is the functionality of this whole tool duplicated by google's facets overview? cc @JosPolfliet https://pair-code.github.io/facets/

**Comment by dartdog** [comment]
Well facets looks promising it is a bit funky at the moment IMHO and there is a certain  nicity to have the capability available in Python :-) IMHO..

**Comment by conradoqg** [comment]
It seems that this fork took a different path by implementing a lot of things related to SQL.

Should we keep this PR active? (It seems that it is not going to be merged anytime soon)

Best

**Comment by romainx** [comment]
I agree with @conradoqg, it will be tricky to merge this PR ...

**Comment by andyreagan** [comment]
@conradoqg @romainx yeah I agree, went a little off the rails trying to get this working on SQL.

I think it's safe to close this PR, with the hope of my finding the time to make these changes on the current state of the project in a cleaner and more principled way.
Do either of you happen to know if the project has changed significantly since I started working on this, back in August?

**Comment by conradoqg** [comment]
Hey

As far as I can tell not much, more refactoring work than structural changes. I think you will not have too many problems reimplementing it in the current version.

Best

**Pull request closed without merging**
