### PR TITLE
feat: Allow empty dataframe

### PR DESCRIPTION
**Pull request by fwd2020-c**
Fixes issue #678 
Work in progress, need to modify tests.
Does this approach look good to you?
Worked on this with @spbail 😄

### CODE REVIEW

**Comment by sbrugman** [comment]
Really good that you're starting contributing to open source :) Feel free to ask if you're unsure about certain parts of the change or contribution process.

A few notes:
- [test] As you mention, it would be good to have a dedicated test for `n=0` (suggestion to add unit tests here: https://github.com/pandas-profiling/pandas-profiling/blob/develop/tests/unit/test_summary_algos.py)
- [test] We would need another test to see if the rendered HTML makes sense.
- [code] The `if df.empty` check can be removed entirely.

**Comment by fwd2020-c** [comment]
Hi Simon,
Thank you so much for your feedback and I followed your instructions to make some changes:

1. [test] As you mention, it would be good to have a dedicated test for n=0 (suggestion to add unit tests here: https://github.com/pandas-profiling/pandas-profiling/blob/develop/tests/unit/test_summary_algos.py)
2.  [code] The if df.empty check can be removed entirely.

However, I have no idea how to create a test to check rendered HTML. 

What do you think?

**Comment by sbrugman** [comment]
Making progress!

The unit tests should add cases for these functions (all affected by removing the exception):
- `get_table_stats` (empty DataFrame)
- `describe_counts`, `describe_generic` and `describe_supported` (empty Series)

I haven't tried running the HTML or Jupyter notebook widgets yet myself, but expect there are quite some parts that should be hidden/empty for empty DFs. We can explicitly test for them in the HTML/Notebooks. If you'd like some feedback, you can either upload a screenshot or the report for an empty dataframe here.

Another thing: you can add the change to the changelog of the next version (`docsrc\source\pages\changelog\2_12_0.rst`). You can put a summary, link to the issue and your github username (e.g. "contributed by @fwd2020-c")

**Comment by fwd2020-c** [comment]
Simon, I created the tests for `describe_counts` , `describe_generic`, `describe_supported`. They passed pytest but I am not very sure it is the right way to test describe_supported which is wrapped by a decorator.

`get_table_stats` needs arg of variable_stats, which is ,I guess, the output of `describe_1d`:
`describe_1d(df, summarizer: BaseSummarizer, typeset: Unsupported)` 
I got an attribute error of "no attribute 'infer_type'"
Is it ok to provide me an example on how to solve this one? 

Attached html report:
http://localhost:8888/view/empty_df_report.html

**Comment by sbrugman** [comment]
`variable_stats` is just a dictionary, you could start with an empty dict and add the testing keys needed.

You've shared a link to the file that only you can access. It should be possible to drag the html file to the comment section and github will upload it for you.

**Comment by fwd2020-c** [comment]
Simon, thank you so much! empty dictionary works! (Out of curiosity, how come empty dictionary can replace the arg of variable_stats: Previously calculated statistic on the DataFrame? 🤔)

http://localhost:8888/view/dragged_empty_df_report.html

**Pull request closed without merging**
