### PR TITLE
Add in html report the image of correlation matrix

### PR DESCRIPTION
**Pull request by phypho**
I tried to add in the html report the images of the correlation matrices (Pearson and Spearman).
The matrix are created in the description result of a data frame, but the integration to the html report doesn't work. Any error is returned.

Here is any example
import pandas as pd                    
import pandas_profiling as pp
import numpy as np
df = pd.DataFrame(np.random.randn(9000).reshape(300,30))
describe_df = pp.describe(df) # works fine

profile = pp.ProfileReport(df)
profile.to_file(outputfile="test.html") # no image in test.html

I am not very comfortable with the template system used here. I am sure I am not far to succeed. Does anyone have any idea how to solve this problem ?
Thanks

### CODE REVIEW

**Comment by etrabelsi** [comment]
Are you guys plan on merge this PR?

**Comment by conradoqg** [comment]
Hey, 

I finished the correlation matrix display (HTML and in Jupyter), please accept the pull request that I did in your fork so we can ask here again to accept this pull request.

Best.

**Comment by romainx** [comment]
Hello,

I just took a look and I have noticed some points.

### First point

I think that we have to check the behavior when `check_correlation=False`.
In this case `dfcorrPear` and `dfcorrSpear` will not be initialized and so the return statement below will throw an error.

```
return {'table': table_stats, 'variables': variable_stats.T, 'freq': {k: df[k].value_counts() for k in df.columns},
           'correlations': {'pearson':dfcorrPear, 'spearman':dfcorrSpear}}
````

### Second point

I think this test will fail since `stats_object` will contain another key `correlations`

```
if set(stats_object.keys()) != {'table', 'variables', 'freq'}:
        raise TypeError("stats_object badly formatted. Did you generate this using the pandas_profiling-eda.describe() function?")
```

Please could check these points and fix them if necessary?

Many thanks.

**Comment by conradoqg** [comment]
Hey,

Thanks for your comments, Sorry, I wasn't clear in my previous comment, I did those fixes (and more), but I made a pull request to @etrabelsi's fork (original change). So when he accepts it on his repo, this one will be updated and then I think we can accept this PR.

Best

**Comment by romainx** [comment]
Hello @conradoqg,

Sorry my bad...

OK let me know when it's done.

**Comment by conradoqg** [comment]
Guys,

Do you mind if I create a new PR with this same improvement since @phypho is not responding? (I need to move my fixes and his improvement to the refactored version, but I can do it in a day)

I hope @phypho doesn't get mad at me 😄 

Best

**Comment by romainx** [comment]
Hello,

I think you can proceed since we have performed major changes in the definition of modules.

Regards

**Comment by conradoqg** [comment]
Hi,

This merge is done in my fork, I'm waiting for PR #82 to be approved so I can create a new pull request with this PR merged to my last changes.

Best

**Comment by romainx** [comment]
Hello,

I close it since it's replace by P3 #83.

**Pull request closed without merging**
