### PR TITLE
checking classes in correlations to avoid division by zero

### PR DESCRIPTION
**Pull request by amarczew**
when len(classes) is zero, an error is raised in correlation_matrix plot function

### CODE REVIEW

**Comment by Aylr** [comment]
@amarczew Is there anything I can do to expedite this? Would you like some tests?

**Comment by amarczew** [comment]
@Aylr I don't think so. I really had to change these lines to continue using it with my dataset when it does not have any correlations. A test for this could be using a dataset without correlations.

**Comment by Aylr** [comment]
@JosPolfliet Is there anything we can do to expedite this being merged?

**Comment by radomirbosak** [comment]
It would be great if we could merge this. The zero division error is quite annoying.

**Comment by JosPolfliet** [comment]
is fixed in the meantime

**Pull request closed without merging**
