### PR TITLE
Add Python 3.8 to Travis

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by gliptak** [comment]
https://github.com/pypa/pip/issues/6275

**Comment by gliptak** [comment]
https://github.com/scipy/scipy/issues/10927

**Comment by gliptak** [comment]
https://github.com/scipy/scipy/issues/6851

**Comment by gliptak** [comment]
https://github.com/scipy/scipy/releases/tag/v1.3.3 was released

**Comment by gliptak** [comment]
https://github.com/numba/llvmlite/issues/527

**Comment by gliptak** [comment]
https://github.com/numba/llvmlite/issues/527#issuecomment-570812533

**Comment by gliptak** [comment]
https://github.com/numpy/numpy/issues/14698

**Comment by sbrugman** [comment]
@gliptak https://github.com/apache/arrow/issues/5987#issuecomment-573778677

**Pull request closed without merging**
